name: rbush
description: RBush — a high-performance R-tree-based 2D spatial index for points and rectangles.
version: 1.1.0
homepage: https://github.com/Zverik/dart_rbush

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.5
